#!/usr/bin/env bash

# Update package lists
apt-get update

# Install Nginx without prompting
apt-get install -y nginx

# Create "index.html"
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80; server {/g' /etc/nginx/sites-available/default

# Restart Nginx (avoid systemctl)
/etc/init.d/nginx restart

# Verify Nginx
service nginx status

# Exit script
exit 0

